# Generated by Django 4.2.6 on 2023-10-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_renter",
            field=models.BooleanField(
                default=False, help_text="Check if user is a UAV owner so renter."
            ),
        ),
    ]
