# Generated by Django 4.2.6 on 2023-10-11 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UavCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, unique=True)),
                ("class_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "operating_altitude",
                    models.FloatField(blank=True, help_text="feet", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UAV Categories",
            },
        ),
        migrations.CreateModel(
            name="UavBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50, unique=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UAV Brands",
            },
        ),
        migrations.CreateModel(
            name="Uav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                (
                    "payload_capacity",
                    models.FloatField(blank=True, help_text="kg", null=True),
                ),
                (
                    "maximum_speed",
                    models.FloatField(blank=True, help_text="knots", null=True),
                ),
                (
                    "wingspan",
                    models.FloatField(blank=True, help_text="meters", null=True),
                ),
                (
                    "endurance",
                    models.FloatField(blank=True, help_text="hours", null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uav_images"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="uavs.uavbrand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uavs.uavcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UAV",
                "verbose_name_plural": "UAVs",
                "unique_together": {("brand", "model")},
            },
        ),
    ]
