# Generated by Django 4.2.6 on 2023-10-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UavCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, unique=True)),
                ("class_name", models.CharField(max_length=50)),
                ("operating_altitude", models.FloatField(help_text="feet")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UAV Categories",
            },
        ),
        migrations.CreateModel(
            name="UavBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50, unique=True)),
                ("country", models.CharField(max_length=50)),
                ("website", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UAV Brands",
            },
        ),
        migrations.CreateModel(
            name="Uav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("payload_capacity", models.FloatField(help_text="kg")),
                ("maximum_speed", models.FloatField(help_text="knots")),
                ("wingspan", models.FloatField(help_text="meters")),
                ("endurance", models.FloatField(help_text="hours")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uav_images"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="uavs.uavbrand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uavs.uavcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UAV",
                "verbose_name_plural": "UAVs",
                "unique_together": {("brand", "model")},
            },
        ),
    ]
