# Generated by Django 4.2.6 on 2023-10-12 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uavs", "0002_uav_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uav",
            name="endurance",
            field=models.FloatField(
                blank=True,
                help_text="hours",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="hourly_rate",
            field=models.FloatField(
                default=0.0,
                help_text="USD",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="maximum_speed",
            field=models.FloatField(
                blank=True,
                help_text="knots",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="payload_capacity",
            field=models.FloatField(
                blank=True,
                help_text="kg",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="wingspan",
            field=models.FloatField(
                blank=True,
                help_text="meters",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="uavcategory",
            name="operating_altitude",
            field=models.FloatField(
                blank=True,
                help_text="feet",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
